AWSTemplateFormatVersion: "2010-09-09"
Description: "Codepipeline-Dynamodb"
Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DynamoDBTable22345
      AttributeDefinitions:
        - AttributeName: 'ID'
          AttributeType: S
        - AttributeName: 'Email'
          AttributeType: S
      KeySchema:
        - AttributeName: 'ID'
          KeyType: HASH
        - AttributeName: 'Email'
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '12'
        WriteCapacityUnits: '12'